name: CI Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1
      - run: yarn install
      - run: yarn lint
      - run: yarn test
        env:
          CI: true
